version: '3.8'

services:
  sample_db:
    image: postgres:12.8
    restart: always
    command: postgres -c 'max_connections=10000'

    container_name: sample_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      APP_DB_USER: ${DB_USER}
      APP_DB_PASSWORD: ${DB_PASSWORD}
      APP_DB_NAME: ${DB_NAME}

    ports:
      - 5434:5432
    volumes:
      - "./pg-data:/var/lib/postgresql/data"
      - ../deploy/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      #- ../deploy/initdb.sh:/script/initdb.sh:rwx
    logging:
        driver: "json-file"
        options:
            max-size: "1g"
            max-file: "3"
  sample:
    depends_on:
      - sample_db
    ports:
      - 127.0.0.1:${LISTEN_PORT}:${LISTEN_PORT}