version: '3.8'

services:

  sample:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
      args:
        LISTEN_PORT: ${LISTEN_PORT}
    image: ${BASE_IMAGE_NAME}/ample:${ENVIRONMENT}
    hostname: ${COMPOSE_PROJECT_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      LISTEN_ADDR: ${LISTEN_ADDR}
      LISTEN_PORT: ${LISTEN_PORT}
      
networks:
  default:
    external: true
    name: sample-network
